version: '3.8'

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    networks:
      - spring-postgres-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Piyush@l1
      POSTGRES_DB: docker-postgres

  postgres_spring:
    build: .
    image: piyush12singh/spring-postgres-docker-image-new12:latest  # Specify your Docker Hub repo/tag
    container_name: postgres_spring
    networks:
      - spring-postgres-net
    ports:
      - "9002:8080"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - spring-postgres-net
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"

networks:
  spring-postgres-net:
    driver: bridge
